service: apollo-lambda
app: mongo-graphql-serverless
org: forestp

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-west-2

functions:
  graphql:
    handler: app.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
          integration: lambda-proxy
      - http:
          path: playground
          method: get
          cors: true
          integration: lambda-proxy
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
